
#- name: Sll check
#  ansible.builtin.import_playbook: playbook-02-get-cert.yaml

#- name: Postgres install
#  ansible.builtin.import_playbook: playbook-03-postgres-check.yaml

- name: Taiga Install Playbook
  hosts: all
  tasks:

    - name: Postgres setup 
      postgres:
        user: 
          name: taiga 
        db_names: 
          - taiga



