- name: Init Script For Servers 
  hosts: all
  tasks:
    - name: Transfer a script file
      ansible.builtin.copy:
        src: ./scripts/00-base-setup-{{ inventory_hostname }}.sh
        dest: /root/
        owner: root
        group: root
        mode: u=rwx,g=rw

    - name: Run a script file
      ansible.builtin.command: /root/00-base-setup-{{ inventory_hostname }}.sh

    - name: Reload openssh
      ansible.builtin.systemd_service:
        name: sshd.service
        state: restarted
